services:

  postgres:
    image: postgres:14
    container_name: postgres_lightning_stats
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lightning_stats
    volumes:
      - postgres_data_lightning_stats:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lightning_stats
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres_data_lightning_stats:
    driver: local
